### ISSUE TITLE
Tarball content is from RESTIC repository

### ISSUE THREAD

**Issue by lucianovk** [FIFTY2Technology/ansible-role-openpbs#1]
After executing ansible-galaxy install fifty2technology.openpbs it was possible to verify the content was from fifty2technology RESTIC repository, the code used by the installation procedure came from tarball: https://github.com/FIFTY2Technology/ansible-role-openpbs/releases/tag/0.52.0 and it is from RESTIC repository.

**Comment by eliba** [comment]
Thank you for reporting this, at the moment I have no idea how this could happen.... Anyways, it's updated with version 0.52.1 :)
